//! TypeScript bindings export (`cargo run --features typegen --bin export-types`).

use std::fs;
use std::io;
use std::path::PathBuf;

use engine_kernel::{PatchSegment, ViewModelPatch};
use ts_rs::TS;

use crate::effect::EffectCommand;
use crate::event::AppEvent;
use crate::protocol::{WorkerInput, WorkerOutput};
use crate::state::{
    DatasetKind, DatasetMeta, FilterDraft, LoadPhase, QueryDraft, QueryMode, QueryPhase,
    QuerySummary, SchemaColumn,
};
use crate::view_model::{ExploreViewModel, PresetOption, SavedViewOption, ViewModel};
use crate::workspace::{
    AppRoute, CrateDetailPhase, CrateDetailSummary, CrateVersionRow, PinnedCrate, SavedView,
};

const GENERATED_HEADER: &str = "// Generated by `npm run generate:types`. Do not edit.\n\n";

pub fn export_types() -> io::Result<()> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../demo/generated");
    fs::create_dir_all(&dir)?;
    let path = dir.join("engine-types.ts");

    let mut out = String::from(GENERATED_HEADER);
    append_decl::<DatasetKind>(&mut out);
    append_decl::<LoadPhase>(&mut out);
    append_decl::<QueryPhase>(&mut out);
    append_decl::<QueryMode>(&mut out);
    append_decl::<SchemaColumn>(&mut out);
    append_decl::<DatasetMeta>(&mut out);
    append_decl::<FilterDraft>(&mut out);
    append_decl::<QueryDraft>(&mut out);
    append_decl::<QuerySummary>(&mut out);
    append_decl::<PresetOption>(&mut out);
    append_decl::<AppRoute>(&mut out);
    append_decl::<SavedView>(&mut out);
    append_decl::<SavedViewOption>(&mut out);
    append_decl::<PinnedCrate>(&mut out);
    append_decl::<CrateDetailPhase>(&mut out);
    append_decl::<CrateVersionRow>(&mut out);
    append_decl::<CrateDetailSummary>(&mut out);
    append_decl::<ExploreViewModel>(&mut out);
    append_decl::<PatchSegment>(&mut out);
    append_decl::<ViewModelPatch>(&mut out);
    append_decl::<AppEvent>(&mut out);
    append_decl::<EffectCommand>(&mut out);
    append_decl::<ViewModel>(&mut out);
    append_decl::<WorkerInput>(&mut out);
    append_decl::<WorkerOutput>(&mut out);

    fs::write(path, out)
}

fn append_decl<T: TS + 'static>(out: &mut String) {
    let decl = T::decl();
    if let Some(rest) = decl.strip_prefix("type ") {
        out.push_str("export type ");
        out.push_str(rest);
    } else {
        out.push_str(&decl);
    }
    out.push_str("\n\n");
}
