//! cbor-x (TS) → ciborium (Rust) fixtures generated by scripts/test-cbor-interop.mjs

use wcol_engine::protocol::{decode_input, decode_output, encode_input, encode_output, WorkerInput};
use wcol_engine::engine::Engine;

fn fixture(name: &str) -> &'static [u8] {
    match name {
        "init" => include_bytes!("../../../scripts/.cbor-fixtures/init.cbor"),
        "url_changed" => include_bytes!("../../../scripts/.cbor-fixtures/url_changed.cbor"),
        "data_drawer_set" => include_bytes!("../../../scripts/.cbor-fixtures/data_drawer_set.cbor"),
        _ => panic!("unknown fixture {name}"),
    }
}

#[test]
fn cbor_x_init_decodes() {
    let bytes = fixture("init");
    let input = decode_input(bytes).expect("cbor-x init should decode in ciborium");
    assert!(matches!(input, WorkerInput::Init));
}

#[test]
fn cbor_x_url_changed_decodes_and_runs() {
    let bytes = fixture("url_changed");
    let input = decode_input(bytes).expect("cbor-x URL_CHANGED should decode");
    let mut engine = Engine::new();
    engine.init();
    let out = engine.handle_input(input);
    let encoded = encode_output(&out);
    decode_output(&encoded).expect("engine output should round-trip");
}

#[test]
fn cbor_x_data_drawer_set_decodes() {
    let bytes = fixture("data_drawer_set");
    decode_input(bytes).expect("cbor-x DATA_DRAWER_SET should decode");
}

#[test]
fn ciborium_output_is_valid_cbor() {
    let input = WorkerInput::Init;
    let bytes = encode_input(&input);
    let decoded = decode_input(&bytes).unwrap();
    assert_eq!(decoded, input);

    let mut engine = Engine::new();
    let out = engine.init();
    let out_bytes = encode_output(&out);
    // Re-decode our own output
    decode_output(&out_bytes).expect("ciborium output self-decode");
}
